import type { SeedAchievement } from "./types";

export const achievements: SeedAchievement[] = [
  {
    code: "first-word",
    titleVi: "Từ đầu tiên",
    description: "Lưu từ vựng đầu tiên của bạn.",
    icon: "🌱",
    xpReward: 20,
    category: "learning",
  },
  {
    code: "words-100",
    titleVi: "100 từ",
    description: "Học được 100 từ vựng.",
    icon: "📚",
    xpReward: 50,
    category: "learning",
  },
  {
    code: "words-500",
    titleVi: "500 từ",
    description: "Học được 500 từ vựng.",
    icon: "📖",
    xpReward: 150,
    category: "learning",
  },
  {
    code: "words-1000",
    titleVi: "1000 từ",
    description: "Học được 1000 từ vựng - con số ấn tượng!",
    icon: "🏆",
    xpReward: 300,
    category: "learning",
  },
  {
    code: "streak-7",
    titleVi: "Streak 7 ngày",
    description: "Giữ mục tiêu liên tiếp 7 ngày.",
    icon: "🔥",
    xpReward: 100,
    category: "streak",
  },
  {
    code: "streak-30",
    titleVi: "Streak 30 ngày",
    description: "Giữ mục tiêu liên tiếp 30 ngày.",
    icon: "🌋",
    xpReward: 500,
    category: "streak",
  },
  {
    code: "quiz-perfect",
    titleVi: "Bài tập hoàn hảo",
    description: "Đạt 100% trong một bài luyện tập.",
    icon: "💯",
    xpReward: 50,
    category: "practice",
  },
  {
    code: "review-50",
    titleVi: "Ôn tập chăm chỉ",
    description: "Hoàn thành 50 lượt ôn tập.",
    icon: "🧠",
    xpReward: 80,
    category: "review",
  },
  {
    code: "hsk1-complete",
    titleVi: "Hoàn thành HSK 1",
    description: "Thành thạo toàn bộ từ vựng HSK 1.",
    icon: "🇨🇳",
    xpReward: 200,
    category: "topic",
  },
  {
    code: "english-starter",
    titleVi: "English Vocabulary Starter",
    description: "Học 30 từ tiếng Anh đầu tiên.",
    icon: "🇬🇧",
    xpReward: 40,
    category: "topic",
  },
  {
    code: "master-10",
    titleVi: "10 từ thành thạo",
    description: "Đưa 10 từ lên trạng thái Thành thạo.",
    icon: "⭐",
    xpReward: 100,
    category: "mastery",
  },
  {
    code: "daily-goal-1",
    titleVi: "Hoàn thành mục tiêu",
    description: "Đạt mục tiêu từ vựng hằng ngày lần đầu tiên.",
    icon: "🎯",
    xpReward: 50,
    category: "daily",
  },
];
