import type { SeedTopic } from "./types";

export const topics: SeedTopic[] = [
  // ---------- ENGLISH ----------
  {
    slug: "giao-tiep-hang-ngay",
    nameVi: "Giao tiếp hằng ngày",
    description: "Từ vựng giao tiếp đời sống: chào hỏi, hỏi đường, xin lỗi, cảm ơn.",
    language: "english",
    emoji: "💬",
    difficulty: 1,
    estMinutes: 8,
  },
  {
    slug: "du-lich",
    nameVi: "Du lịch",
    description: "Từ vựng sân bay, khách sạn, hành lý và những chuyến đi.",
    language: "english",
    emoji: "✈️",
    difficulty: 2,
    estMinutes: 10,
  },
  {
    slug: "business",
    nameVi: "Business",
    description: "Đàm phán, hợp đồng, doanh thu và môi trường kinh doanh.",
    language: "english",
    emoji: "💼",
    difficulty: 4,
    estMinutes: 12,
  },
  {
    slug: "cong-nghe",
    nameVi: "Công nghệ",
    description: "Phần mềm, thiết bị, trí tuệ nhân tạo và an ninh mạng.",
    language: "english",
    emoji: "💻",
    difficulty: 3,
    estMinutes: 10,
  },
  {
    slug: "giao-duc",
    nameVi: "Giáo dục",
    description: "Trường lớp, bài tập, học bổng và quá trình học tập.",
    language: "english",
    emoji: "🎓",
    difficulty: 2,
    estMinutes: 10,
  },
  {
    slug: "do-an",
    nameVi: "Đồ ăn",
    description: "Thực đơn, gia vị, cảm giác về hương vị và nhà hàng.",
    language: "english",
    emoji: "🍜",
    difficulty: 1,
    estMinutes: 8,
  },
  {
    slug: "mua-sam",
    nameVi: "Shopping",
    description: "Giá cả, giảm giá, đổi trả và mua sắm trực tuyến.",
    language: "english",
    emoji: "🛍️",
    difficulty: 1,
    estMinutes: 8,
  },
  {
    slug: "cong-viec",
    nameVi: "Công việc",
    description: "Văn phòng, phỏng vấn, lương thưởng và sự nghiệp.",
    language: "english",
    emoji: "🧑‍💼",
    difficulty: 3,
    estMinutes: 10,
  },
  {
    slug: "ielts",
    nameVi: "IELTS",
    description: "Từ vựng học thuật cho Writing và Speaking band cao.",
    language: "english",
    emoji: "🎯",
    difficulty: 5,
    estMinutes: 15,
  },
  {
    slug: "toeic",
    nameVi: "TOEIC",
    description: "Từ vựng thương mại cho bài thi Nghe - Đọc TOEIC.",
    language: "english",
    emoji: "📝",
    difficulty: 3,
    estMinutes: 12,
  },

  // ---------- CHINESE ----------
  {
    slug: "hsk-1",
    nameVi: "HSK 1",
    description: "150 từ cơ bản nhất theo chuẩn HSK 1.",
    language: "chinese",
    emoji: "🌱",
    difficulty: 1,
    estMinutes: 8,
  },
  {
    slug: "hsk-2",
    nameVi: "HSK 2",
    description: "Từ vựng HSK 2: chuẩn bị, kiểm tra, nâng cao.",
    language: "chinese",
    emoji: "🌿",
    difficulty: 2,
    estMinutes: 10,
  },
  {
    slug: "hsk-3",
    nameVi: "HSK 3",
    description: "Từ vựng HSK 3: phát triển, văn hóa, môi trường.",
    language: "chinese",
    emoji: "🍀",
    difficulty: 3,
    estMinutes: 12,
  },
  {
    slug: "hsk-4",
    nameVi: "HSK 4",
    description: "Từ vựng HSK 4: đàm phán, cải thiện, cạnh tranh.",
    language: "chinese",
    emoji: "🌳",
    difficulty: 4,
    estMinutes: 14,
  },
  {
    slug: "hsk-5",
    nameVi: "HSK 5",
    description: "Từ vựng HSK 5: chiến lược, nền tảng, linh hoạt.",
    language: "chinese",
    emoji: "🌲",
    difficulty: 5,
    estMinutes: 16,
  },
  {
    slug: "hsk-6",
    nameVi: "HSK 6",
    description: "Từ vựng HSK 6: thành ngữ, sách báo, học thuật.",
    language: "chinese",
    emoji: "🏔️",
    difficulty: 5,
    estMinutes: 18,
  },
  {
    slug: "giao-tiep-tq",
    nameVi: "Giao tiếp",
    description: "Lời chào, cảm ơn, xin lỗi và các câu giao tiếp thông dụng.",
    language: "chinese",
    emoji: "🗣️",
    difficulty: 1,
    estMinutes: 8,
  },
  {
    slug: "du-lich-tq",
    nameVi: "Du lịch",
    description: "Máy bay, khách sạn, visa và những chuyến đi.",
    language: "chinese",
    emoji: "🧳",
    difficulty: 2,
    estMinutes: 10,
  },
  {
    slug: "cong-viec-tq",
    nameVi: "Công việc",
    description: "Họp hành, lương bổng, dự án và môi trường công sở.",
    language: "chinese",
    emoji: "🏢",
    difficulty: 3,
    estMinutes: 12,
  },
  {
    slug: "do-an-tq",
    nameVi: "Đồ ăn",
    description: "Món ăn Trung Hoa, gia vị và thực đơn nhà hàng.",
    language: "chinese",
    emoji: "🥟",
    difficulty: 1,
    estMinutes: 8,
  },
];
